(function () {
  const CAMERA_LINKS = {
    mdot: 'https://mdotjboss.state.mi.us/MiDrive/map',
    usgsWebcams: 'https://www.usgs.gov/products/multimedia-gallery/webcams',
    usgsIv: 'https://waterservices.usgs.gov/nwis/iv/',
    noaa: 'https://water.noaa.gov/',
    egle: 'https://gis-egle.hub.arcgis.com/datasets/egle::michigan-dam-inventory/about',
    dnr: 'https://www.michigan.gov/dnr',
    nws: 'https://www.weather.gov/',
  };

  const CAMERA_FEEDS = [
    {
      id: 'cam-edenville-down-river',
      label: 'Edenville Down River',
      provider: 'CamStreamer',
      group: 'Four Lakes restoration',
      view: 'Downstream river channel below Edenville Dam.',
      bestFor: 'Water movement and downstream channel conditions.',
      confidence: 'verified public embed',
      relatedDamIds: ['dam-15'],
      pageUrl: 'https://camstreamer.com/live/stream/25036-edenville-down-river',
      embedUrl: 'https://camstreamer.com/embed/644e1e1e3d259a8/S-62396?rel=0',
      note: 'Public live stream near Edenville Dam, Beaverton.',
    },
    {
      id: 'cam-tobacco-river-m30',
      label: 'Tobacco River Dam and M-30 Bridge',
      provider: 'YouTube',
      group: 'Four Lakes restoration',
      view: 'Tobacco River side near M-30 bridge and the Edenville/Wixom Lake area.',
      bestFor: 'Bridge, road-adjacent water, and restoration visibility.',
      confidence: 'verified public video',
      relatedDamIds: ['dam-15'],
      pageUrl: 'https://www.youtube.com/watch?v=Pc-4Pk-wbeM',
      embedUrl: 'https://www.youtube.com/embed/Pc-4Pk-wbeM',
      note: 'Public 24/7 stream covering the Tobacco River side of the Edenville/Wixom Lake area.',
    },
    {
      id: 'cam-sanford-dam-park',
      label: 'Sanford Dam and Park Area',
      provider: 'CamStreamer',
      group: 'Four Lakes restoration',
      view: 'Sanford Dam park area and nearby lake restoration zone.',
      bestFor: 'Park area, lake bed, and visible project activity.',
      confidence: 'verified public embed',
      relatedDamIds: ['dam-17'],
      pageUrl: 'https://camstreamer.com/live/stream/28700-sanford-dam-and-park-area-michigan',
      embedUrl: 'https://camstreamer.com/embed/iLyjAgdd5F4ccnbXaGw8oc3tLTIZiNXhSBKHt17M?rel=0',
      note: 'Public 24/7 HD live stream near Sanford Dam and park area.',
    },
    {
      id: 'cam-secord-dam',
      label: 'Secord Dam',
      provider: 'CamStreamer',
      group: 'Four Lakes restoration',
      view: 'Secord Dam work area and river corridor.',
      bestFor: 'Dam work area and river corridor visibility.',
      confidence: 'verified public embed',
      relatedDamIds: ['dam-18'],
      pageUrl: 'https://camstreamer.com/live/stream/93899083-secord-dam-michigan',
      embedUrl: 'https://camstreamer.com/embed/GznXQbX8XHOdpfKI6LZRdF5RllLXgflyFiyHfNNk?rel=0',
      note: 'Public live stream near Secord Dam in Gladwin County.',
    },
    {
      id: 'cam-smallwood-dam',
      label: 'Smallwood Dam',
      provider: 'YouTube',
      group: 'Four Lakes restoration',
      view: 'Smallwood Dam work area and downstream channel.',
      bestFor: 'Work area, downstream channel, and lake restoration visibility.',
      confidence: 'verified public video',
      relatedDamIds: ['dam-16'],
      pageUrl: 'https://www.youtube.com/watch?v=qLkw-CS9FQE',
      embedUrl: 'https://www.youtube.com/embed/qLkw-CS9FQE',
      note: 'Public 24/7 stream near Smallwood Dam.',
    },
  ];

  const EMBEDDED_DAMS = [
    { id: 'dam-1', DamName: 'Hardy Dam', County: 'Newaygo', River: 'Muskegon River', OwnerName: 'Consumers Energy', DownstreamHazardPotential: 'High', ConditionAssessment: 'Fair', Latitude: 43.5147, Longitude: -85.6421, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-2', DamName: 'Croton Dam', County: 'Newaygo', River: 'Muskegon River', OwnerName: 'Consumers Energy', DownstreamHazardPotential: 'High', ConditionAssessment: 'Fair', Latitude: 43.4216, Longitude: -85.6683, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-3', DamName: 'Mio Dam', County: 'Oscoda', River: 'Au Sable River', OwnerName: 'Consumers Energy', DownstreamHazardPotential: 'High', ConditionAssessment: 'Fair', Latitude: 44.6522, Longitude: -84.1297, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-4', DamName: 'Tippy Dam', County: 'Manistee', River: 'Manistee River', OwnerName: 'Consumers Energy', DownstreamHazardPotential: 'High', ConditionAssessment: 'Fair', Latitude: 44.3337, Longitude: -85.8922, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-5', DamName: 'Alpena Dam', County: 'Alpena', River: 'Thunder Bay River', OwnerName: 'City of Alpena', DownstreamHazardPotential: 'Significant', ConditionAssessment: 'Fair', Latitude: 45.0561, Longitude: -83.4323, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-6', DamName: 'Foote Dam', County: 'Iosco', River: 'Au Sable River', OwnerName: 'Consumers Energy', DownstreamHazardPotential: 'High', ConditionAssessment: 'Fair', Latitude: 44.4163, Longitude: -83.7788, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-7', DamName: 'Cheboygan Dam', County: 'Cheboygan', River: 'Cheboygan River', OwnerName: 'Local operator', DownstreamHazardPotential: 'High', ConditionAssessment: 'Fair', Latitude: 45.6467, Longitude: -84.4749, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-8', DamName: 'Tower Dam', County: 'Cheboygan', River: 'Black River', OwnerName: 'Local operator', DownstreamHazardPotential: 'Significant', ConditionAssessment: 'Fair', Latitude: 45.4976, Longitude: -84.2987, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-9', DamName: 'Chandler Dam', County: 'Charlevoix', River: 'Boyne River', OwnerName: 'Local operator', DownstreamHazardPotential: 'Significant', ConditionAssessment: 'Fair', Latitude: 45.1566, Longitude: -85.1174, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-10', DamName: 'Burt Dam', County: 'Cheboygan', River: 'Crooked River', OwnerName: 'Local authority', DownstreamHazardPotential: 'Significant', ConditionAssessment: 'Fair', Latitude: 45.4701, Longitude: -84.6934, DamType: 'Control structure', Purposes: 'Navigation / water control' },
    { id: 'dam-11', DamName: 'Morrow Dam', County: 'Kalamazoo', River: 'Kalamazoo River', OwnerName: 'Hydroelectric operator', DownstreamHazardPotential: 'High', ConditionAssessment: 'Fair', Latitude: 42.3259, Longitude: -85.3828, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-12', DamName: 'Allegan Dam', County: 'Allegan', River: 'Kalamazoo River', OwnerName: 'Hydroelectric operator', DownstreamHazardPotential: 'High', ConditionAssessment: 'Fair', Latitude: 42.5312, Longitude: -85.8552, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-13', DamName: 'Buchanan Dam', County: 'Berrien', River: 'St. Joseph River', OwnerName: 'Hydroelectric operator', DownstreamHazardPotential: 'High', ConditionAssessment: 'Fair', Latitude: 41.8267, Longitude: -86.3603, DamType: 'Concrete', Purposes: 'Hydroelectric' },
    { id: 'dam-14', DamName: 'Ludington Pumped Storage', County: 'Mason', River: 'Lake Michigan Shoreline', OwnerName: 'Consumers Energy', DownstreamHazardPotential: 'High', ConditionAssessment: 'Good', Latitude: 43.9495, Longitude: -86.4412, DamType: 'Embankment / concrete', Purposes: 'Pumped storage' },
    { id: 'dam-15', DamName: 'Edenville Dam', County: 'Midland', River: 'Tittabawassee River', OwnerName: 'Former hydro / redevelopment area', DownstreamHazardPotential: 'High', ConditionAssessment: 'Poor', Latitude: 43.8009, Longitude: -84.3855, DamType: 'Earthfill', Purposes: 'Former hydroelectric / impoundment', WebcamUrl: CAMERA_FEEDS[0].pageUrl, WebcamEmbed: CAMERA_FEEDS[0].embedUrl },
    { id: 'dam-16', DamName: 'Smallwood Dam', County: 'Gladwin', River: 'Tittabawassee River', OwnerName: 'Local / lake authority', DownstreamHazardPotential: 'High', ConditionAssessment: 'Unsatisfactory', Latitude: 43.9600, Longitude: -84.3353, DamType: 'Earth gravity', Purposes: 'Water control / recreation' },
    { id: 'dam-17', DamName: 'Sanford Dam', County: 'Midland', River: 'Tittabawassee River', OwnerName: 'Four Lakes Task Force / local lake authority', DownstreamHazardPotential: 'High', ConditionAssessment: 'Poor', Latitude: 43.6727, Longitude: -84.3807, DamType: 'Earthfill / concrete spillway', Purposes: 'Former hydroelectric / impoundment', WebcamUrl: CAMERA_FEEDS[2].pageUrl, WebcamEmbed: CAMERA_FEEDS[2].embedUrl },
    { id: 'dam-18', DamName: 'Secord Dam', County: 'Gladwin', River: 'Tittabawassee River', OwnerName: 'Four Lakes Task Force / local lake authority', DownstreamHazardPotential: 'High', ConditionAssessment: 'Unsatisfactory', Latitude: 44.0433, Longitude: -84.3417, DamType: 'Earth gravity', Purposes: 'Hydroelectric / impoundment' },
  ];

  const EMBEDDED_GAUGES = [
    { id: 'g-1', usgsId: '04121970', name: 'Muskegon River near Hardy Dam', lat: 43.5162, lon: -85.6399, values: [7.4, 7.5, 7.6, 7.7, 7.8, 7.8, 7.9, 8.0, 8.0, 8.1, 8.2, 8.2] },
    { id: 'g-2', usgsId: '04121650', name: 'Muskegon River near Croton', lat: 43.4242, lon: -85.6648, values: [6.2, 6.1, 6.3, 6.4, 6.4, 6.5, 6.6, 6.6, 6.7, 6.7, 6.8, 6.8] },
    { id: 'g-3', usgsId: '04136500', name: 'Au Sable River near Mio', lat: 44.6508, lon: -84.1325, values: [4.8, 4.9, 4.9, 5.0, 5.1, 5.1, 5.2, 5.3, 5.3, 5.4, 5.5, 5.5] },
    { id: 'g-4', usgsId: '04125500', name: 'Manistee River at Tippy Dam', lat: 44.3315, lon: -85.8953, values: [9.3, 9.2, 9.4, 9.5, 9.5, 9.6, 9.7, 9.8, 9.8, 9.9, 10.0, 10.1] },
    { id: 'g-5', usgsId: '04135000', name: 'Thunder Bay River at Alpena', lat: 45.0601, lon: -83.4277, values: [3.2, 3.2, 3.3, 3.3, 3.4, 3.4, 3.4, 3.5, 3.5, 3.6, 3.6, 3.6] },
    { id: 'g-6', usgsId: '04137305', name: 'Au Sable River near Foote Dam', lat: 44.4148, lon: -83.7761, values: [5.1, 5.1, 5.2, 5.2, 5.3, 5.3, 5.4, 5.5, 5.5, 5.6, 5.7, 5.7] },
    { id: 'g-7', usgsId: '04132052', name: 'Cheboygan River near Cheboygan', lat: 45.6462, lon: -84.4758, values: [4.0, 4.0, 4.1, 4.1, 4.2, 4.2, 4.3, 4.3, 4.4, 4.5, 4.5, 4.6] },
    { id: 'g-8', usgsId: '04127918', name: 'Black River near Tower', lat: 45.4990, lon: -84.3003, values: [3.8, 3.8, 3.9, 4.0, 4.0, 4.1, 4.2, 4.2, 4.3, 4.4, 4.4, 4.5] },
    { id: 'g-9', usgsId: '04127800', name: 'Boyne River near Boyne Falls', lat: 45.1687, lon: -85.1145, values: [2.8, 2.9, 2.9, 3.0, 3.0, 3.1, 3.1, 3.2, 3.2, 3.3, 3.3, 3.4] },
    { id: 'g-10', usgsId: '04108660', name: 'Kalamazoo River near Morrow Dam', lat: 42.3274, lon: -85.3842, values: [5.6, 5.6, 5.7, 5.7, 5.8, 5.9, 5.9, 6.0, 6.0, 6.1, 6.1, 6.2] },
    { id: 'g-11', usgsId: '04108800', name: 'Kalamazoo River near Allegan', lat: 42.5299, lon: -85.8537, values: [6.1, 6.1, 6.2, 6.2, 6.3, 6.4, 6.4, 6.5, 6.5, 6.6, 6.7, 6.7] },
    { id: 'g-12', usgsId: '04102000', name: 'St. Joseph River near Buchanan', lat: 41.8280, lon: -86.3587, values: [7.8, 7.8, 7.9, 8.0, 8.0, 8.1, 8.2, 8.2, 8.3, 8.4, 8.4, 8.5] },
    { id: 'g-13', usgsId: '04156000', name: 'Tittabawassee River near Edenville', lat: 43.8018, lon: -84.3848, values: [10.0, 10.1, 10.2, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11.0] },
    { id: 'g-14', usgsId: '04155900', name: 'Tittabawassee River near Smallwood', lat: 43.9641, lon: -84.4840, values: [8.6, 8.7, 8.7, 8.8, 8.9, 8.9, 9.0, 9.1, 9.1, 9.2, 9.3, 9.4] },
  ].map((gauge) => ({
    ...gauge,
    sourceInfo: { usgsId: gauge.usgsId, name: gauge.name, lat: gauge.lat, lon: gauge.lon },
    values: gauge.values.map((value, index) => ({
      value,
      dateTime: new Date(Date.now() - (11 - index) * 3600000).toISOString(),
    })),
  }));

  window.DAM_WATCH_DATA = {
    michiganCenter: [44.3148, -85.6024],
    defaultStageLimit: 25,
    links: CAMERA_LINKS,
    cameraFeeds: CAMERA_FEEDS,
    dams: EMBEDDED_DAMS,
    gauges: EMBEDDED_GAUGES,
    alerts: [],
  };
}());
